@startuml
class Command {
  +Execute(): virtual void = 0
}
class Invoker {
  -_commands
  +StoreAndExecute(Command *command): void
}
class Cliente {
  -id: int
  -nombre: string
  -apellido: string
  -forma_de_contacto: string
  -correo: string
  -telefono: string
  -calle: string
  -numero: int
  -colonia: string
  +mandarCorreo(): void
  +enviarSms(): void
  +realizarLlamada(): void
}

class MandarCorreo {

}
class EnviarSMS {

}
class RealizarLlamada {

}

Invoker o-- Command
Command ^-- MandarCorreo
Command ^-- EnviarSMS
Command ^-- RealizarLlamada

MandarCorreo --> Cliente
EnviarSMS --> Cliente
RealizarLlamada --> Cliente

@enduml
